apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci2
  labels:
    app: ci2
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: ci2
  replicas: 1
  template:
    metadata:
      labels:
        app: ci2
        hail.is/sha: "{{ code.sha }}"
    spec:
      containers:
        - name: ci2
          image: "{{ ci_image.image }}"
          env:
            - name: HAIL_CI2_OAUTH_TOKEN
              value: /secrets/oauth-token/oauth-token
{% if deploy %}
            - name: HAIL_WATCHED_BRANCHES
              value: '[["hail-is/hail:master",true]]'
{% else %}
            - name: HAIL_WATCHED_BRANCHES
              value: '[]'
{% endif %}
            - name: BATCH_SERVER_URL
              value: http://batch.{{ default_ns.name }}
            - name: HAIL_GCP_PROJECT
              value: "{{ global.project }}"
            - name: HAIL_CI_UTILS_IMAGE
              value: "{{ ci_utils_image.image }}"
            - name: HAIL_IP
              value: "{{ global.ip }}"
            - name: HAIL_DOMAIN
              value: "{{ global.domain }}"
            - name: HAIL_TOKEN_FILE
              value: '/ci2-jwt/jwt'
            - name: HAIL_SELF_HOSTNAME
              value: ci2
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /secrets/oauth-token
              readOnly: true
              name: hail-ci-0-1-github-oauth-token
            - mountPath: /ci2-jwt
              readOnly: true
              name: ci2-jwt
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: hail-ci-0-1-github-oauth-token
          secret:
            secretName: hail-ci-0-1-github-oauth-token
        - name: ci2-jwt
          secret:
            secretName: user-jwt-fzp4f
---
apiVersion: v1
kind: Service
metadata:
  name: ci2
  labels:
    app: ci2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ci2
