apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: notebook-deployment
  labels:
    app: notebook
    hail.is/sha: "6088ddf08ae2"
spec:
  selector:
    matchLabels:
      app: notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook
        hail.is/sha: "6088ddf08ae2"
    spec:
      containers:
      - name: notebook
        image: gcr.io/broad-ctsa/notebook:1ec81bb6fdd5c850c851211dd547bc2339ae13fa7c5669ce27dd2410cfb17e72
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: notebook
