apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: scorecard-deployment
spec:
  selector:
    matchLabels:
      app: scorecard
  replicas: 1
  template:
    metadata:
      labels:
        app: scorecard
    spec:
      containers:
      - name: scorecard
        image: gcr.io/broad-ctsa/scorecard
        ports:
        - containerPort: 5000
          volumeMounts:
            - mountPath: /hail-ci/oauth-token
              readOnly: true
              name: hail-ci-0-1-github-oauth-token
        volumeMounts:
          - mountPath: /secrets
            readOnly: true
            name: scorecard-github-access-token
    volumes:
      - name: 
        secret:
          secretName: scorecard-github-access-token
---
apiVersion: v1
kind: Service
metadata:
  name: scorecard
  labels:
    app: scorecard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: scorecard
  loadBalancerIP: 35.202.189.158 # scorecard
  type: LoadBalancer
