apiVersion: v1
kind: Pod
metadata:
  name: letsencrypt-run
  labels:
    app: site
spec:
  containers:
  - name: letsencrypt-run
    command: ["/bin/bash"]
    args: ["-c", "/etc/init.d/nginx start; rm -rf /etc/letsencrypt/*; sleep 5; certbot -n --agree-tos -m cseed@broadinstitute.org -d test.hail.is --nginx"]
    image: gcr.io/broad-ctsa/letsencrypt-run
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /etc/letsencrypt
        name: letsencrypt-certs
  restartPolicy: Never
  volumes:
    - name: letsencrypt-certs
      persistentVolumeClaim:
        claimName: letsencrypt-certs
