---
apiVersion: v1
kind: Service
metadata:
  name: upload
  labels:
    app: upload
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: upload
---
<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: notebook
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  ports:
   - port: 443
     protocol: TCP
     targetPort: 5000
  selector:
    app: auth
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  ports:
   - port: 443
     protocol: TCP
     targetPort: 443
  selector:
    app: blog
---
apiVersion: v1
kind: Service
metadata:
  name: workshop
  labels:
    app: workshop
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: notebook
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 5000
  selector:
    app: hello
---
apiVersion: v1
kind: Service
metadata:
  name: query
  labels:
    app: query
spec:
  ports:
  - name: query
    port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: query
---
apiVersion: v1
kind: Service
metadata:
  name: memory
  labels:
    app: memory
spec:
  ports:
  - name: memory
    port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: memory
---
apiVersion: v1
kind: Service
metadata:
  name: address
  labels:
    app: address
spec:
  ports:
  - name: address
    port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: address
---
apiVersion: v1
kind: Service
metadata:
  name: shuffler
  labels:
    app: shuffler
spec:
  ports:
  - name: shuffler
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: shuffler
---
apiVersion: v1
kind: Service
metadata:
  name: atgu
  labels:
    app: atgu
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: atgu
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
   - port: 443
     protocol: TCP
     targetPort: 443
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
   - port: 443
     protocol: TCP
     targetPort: 443
  selector:
    app: prometheus
---
=======
>>>>>>> dca6c871a... [router] move Service yaml into their own deployment definitions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  labels:
    app: router
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: router
  replicas: 3
  template:
    metadata:
      labels:
        app: router
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - router
              topologyKey: "kubernetes.io/hostname"
      containers:
       - name: router
         image: {{ router_image.image }}
         resources:
           requests:
             cpu: "20m"
             memory: "20M"
           limits:
             cpu: "1"
             memory: "1G"
         env:
          - name: HAIL_DOMAIN
            value: {{ global.domain }}
          - name: HAIL_DEFAULT_NAMESPACE
            value: {{ default_ns.name }}
         ports:
          - containerPort: 443
         volumeMounts:
          - name: ssl-config-router
            mountPath: /ssl-config
            readOnly: true
         readinessProbe:
           tcpSocket:
             port: 443
           initialDelaySeconds: 5
           periodSeconds: 5
      volumes:
       - name: ssl-config-router
         secret:
           optional: false
           secretName: ssl-config-router
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: router
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: router
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: router
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: router
