apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  selector:
    matchLabels:
      app: apiserver
  replicas: 1
  template:
    metadata:
      labels:
        app: apiserver
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
        - name: apiserver
          image: "{{ apiserver_image.image }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          volumeMounts:
          - mountPath: /hail-vdc-sa-key
            name: hail-vdc-sa-key
          - name: jwt-secret-key
            mountPath: /jwt-secret-key
            readOnly: true
          resources:
            requests:
              memory: "3.75G"
              cpu: "0.9"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: hail-vdc-sa-key
          secret:
            secretName: hail-vdc-sa-key
        - name: jwt-secret-key
          secret:
            secretName: jwt-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  ports:
  - name: hail
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: apiserver
