apiVersion: v1
kind: Pod
metadata:
  name: create-batch-tables
spec:
  containers:
  - name: create-batch-tables
    image: "{{ create_batch_tables_image.image }}"
    command:
     - /bin/bash
     - -c
     - |
       set -x
       # index creation isn't idempotent, don't create if a table exists
       echo 'SELECT 1 FROM jobs WHERE FALSE;' | mysql --defaults-extra-file=/secrets/batch-admin/sql-config.cnf
       if [ "$?" != "0" ]; then
         set -e
         mysql --defaults-extra-file=/secrets/batch-admin/sql-config.cnf < ./create-batch-tables.sql
       fi
    volumeMounts:
      - mountPath: /secrets/batch-admin
        readOnly: true
        name: batch-admin-secret
  volumes:
    - name: batch-admin-secret
      secret:
        secretName: "{{ batch_database.admin_secret_name }}"
  restartPolicy: Never
