apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: batch
  labels:
    app: batch
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: batch
  replicas: 1
  template:
    metadata:
      labels:
        app: batch
        hail.is/sha: "{{ code.sha }}"
    spec:
      serviceAccountName: batch
      containers:
      - name: batch
        image: "{{ batch_image.image }}"
        resources:
          requests:
            memory: "1G"
            cpu: "1"
        env:
         - name: HAIL_POD_NAMESPACE
           value: "{{ batch_pods_ns.name }}"
         - name: HAIL_JWT_SECRET_KEY_FILE
           value: /jwt-secret/secret-key
{% if deploy %}
         - name: HAIL_INSTANCE_ID
           value: cd50b95a89914efb897965a5e982a29d
{% endif %}
        ports:
         - containerPort: 5000
        volumeMounts:
         - name: batch-user-secret
           mountPath: /batch-user-secret
           readOnly: true
         - name: jwt-secret
           mountPath: /jwt-secret
           readOnly: true
         - name: gsa-key
           mountPath: /batch-gsa-key
           readOnly: true
         - name: jwt
           mountPath: /batch-jwt
           readOnly: true
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
       - name: batch-user-secret
         secret:
           optional: false
           secretName: "{{ batch_database.user_secret_name }}"
       - name: jwt-secret
         secret:
           optional: false
           secretName: notebook-secrets
       - name: gsa-key
         secret:
           optional: false
           secretName: gsa-key-n6hf9
       - name: jwt
         secret:
           optional: false
           secretName: user-jwt-fh7kp
---
apiVersion: v1
kind: Service
metadata:
  name: batch
  labels:
    app: batch
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: batch
