name: hail-batch
dependencies:
- python=3.6
- werkzeug
- flask
- pip
- pip:
  - cerberus
  - flake8
  - kubernetes
  - pylint
  - pytest
  - requests
  - asyncio
  - aiohttp
  - aiodns
  - cchardet
  - aiohttp_jinja2
  - jinja2
