apiVersion: v1
kind: Pod
metadata:
  name: test-batch
spec:
  containers:
  - name: test-batch
    image: "{{ test_batch_image.image }}"
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HAIL_TOKEN_FILE
      value: '/jwt/jwt'
    volumeMounts:
      - mountPath: /jwt
        readOnly: true
        name: test-batch-jwt
  volumes:
    - name: test-batch-jwt
      secret:
        secretName: user-jwt-vkqfw
  restartPolicy: Never
