apiVersion: v1
kind: Namespace
metadata:
  name: test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test
  name: test-test
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-svc-test-test-binding
  namespace: test
subjects:
- kind: ServiceAccount
  name: test-svc
  namespace: batch-pods
roleRef:
  kind: Role
  name: test-test
  apiGroup: "rbac.authorization.k8s.io"
