apiVersion: v1
kind: Pod
metadata:
  name: test-batch
spec:
  containers:
  - name: test-batch
    image: "{{ test_batch_image.image }}"
    env:
     - name: POD_IP
       valueFrom:
         fieldRef:
           fieldPath: status.podIP
     - name: HAIL_TOKEN_FILE
       value: '/jwt/jwt'
     - name: BATCH_URL
       value: http://batch.{{ default_ns.name }}
    volumeMounts:
      - mountPath: /jwt
        readOnly: true
        name: test-batch-jwt
      - name: batch-user-secret
        mountPath: /batch-user-secret
        readOnly: true
  volumes:
    - name: batch-user-secret
      secret:
        optional: false
        secretName: "{{ batch_database.user_secret_name }}"
    - name: test-batch-jwt
      secret:
        secretName: user-jwt-vkqfw
  restartPolicy: Never
