apiVersion: v1
kind: Pod
metadata:
  name: test-batch
spec:
  containers:
  - name: test-batch
    image: "{{ test_batch_image.image }}"
    env:
     - name: POD_IP
       valueFrom:
         fieldRef:
           fieldPath: status.podIP
     - name: HAIL_LOCATION
       value: k8s
    volumeMounts:
      - mountPath: /deploy-config
        readOnly: true
        name: deploy-config
      - mountPath: /user-tokens
        readOnly: true
        name: test-jwt
  volumes:
    - name: deploy-config
      secret:
        secretName: deploy-config
    - name: test-jwt
      secret:
        secretName: test-jwt
  restartPolicy: Never
