apiVersion: v1
kind: Pod
metadata:
  name: create-deploy-config
spec:
  serviceAccount: admin
  containers:
  - name: create-deploy-config
    image: "{{ base_image.image }}"
    command:
     - /bin/bash
     - -c
     - |
       set -ex
       cat > deploy-config.json <<EOF
       {"location":"k8s","default_namespace":"{{ default_ns.name }}","service_namespace":{}}
       EOF
       kubectl -n {{ default_ns.name }} create secret generic deploy-config --from-file=./deploy-config.json
       kubectl -n {{ batch_pods_ns.name }} create secret generic deploy-config --from-file=./deploy-config.json
  restartPolicy: Never
