apiVersion: v1
kind: Pod
metadata:
  name: test-pipeline
spec:
  containers:
  - name: test-pipeline
    image: "{{ test_pipeline_image.image }}"
    env:
     - name: HAIL_LOCATION
       value: k8s
     - name: SCRATCH
       value: gs://hail-test-1c9nm/{{ setup_pipeline.token }}/pipeline
    volumeMounts:
      - mountPath: /deploy-config
        readOnly: true
        name: deploy-config
      - mountPath: /user-tokens
        readOnly: true
        name: test-jwt
  volumes:
    - name: deploy-config
      secret:
        secretName: deploy-config
    - name: test-jwt
      secret:
        secretName: test-jwt
  restartPolicy: Never
