apiVersion: v1
kind: Pod
metadata:
  name: test-pipeline
spec:
  containers:
  - name: test-pipeline
    image: "{{ test_pipeline_image.image }}"
    resources:
      requests:
        memory: "2G"
        cpu: "2"
    env:
     - name: HAIL_TOKEN_FILE
       value: '/test-jwt/jwt'
     - name: BATCH_URL
       value: http://batch.{{ default_ns.name }}
     - name: SCRATCH
       value: gs://hail-test-1c9nm/{{ setup_pipeline.token }}/pipeline
    volumeMounts:
      - mountPath: /test-jwt
        readOnly: true
        name: test-jwt
  volumes:
    - name: test-jwt
      secret:
        secretName: test-jwt
  restartPolicy: Never
