apiVersion: v1
kind: Pod
metadata:
  name: test-pipeline
spec:
  containers:
  - name: test-pipeline
    image: "{{ test_pipeline_image.image }}"
    env:
     - name: BATCH_URL
       value: http://batch.{{ default_ns.name }}
  restartPolicy: Never
