apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook2
  labels:
    app: notebook2
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: notebook2
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook2
        hail.is/sha: "{{ code.sha }}"
    spec:
      serviceAccountName: notebook
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
       - name: notebook2
         image: "{{ notebook2_image.image }}"
         env:
          - name: HAIL_DEPLOY_CONFIG_FILE
            value: /deploy-config/deploy-config.json
          - name: HAIL_NOTEBOOK2_WORKER_IMAGE
            value: "{{ hail_jupyter_image.image }}"
         ports:
          - containerPort: 5000
         volumeMounts:
          - name: deploy-config
            mountPath: /deploy-config
            readOnly: true
      volumes:
       - name: deploy-config
         secret:
           optional: false
           secretName: deploy-config
---
apiVersion: v1
kind: Service
metadata:
  name: notebook2
  labels:
    app: notebook2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: notebook2
