name: hail-py3.7
dependencies:
- python=3.7
- Sphinx>=1.8.1
- sphinxcontrib>=1.0
- conda-forge::nbsphinx>=0.3.5
- conda-forge::sphinx_rtd_theme>=0.4.2
- numpy>=1.15.3
- pandas>=0.23.4
- matplotlib>=3.0.1
- seaborn>=0.9.0
- bokeh>=1.0.0
- jupyter>=1.0.0
- pip>=18.1
- pytest>=3.9.2
- pip:
    - parsimonious>=0.8.1
    - ipykernel>=4.9.0
    - pytest-xdist>=1.22.2
    - decorator>=4.3.0
