apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: site-deployment
spec:
  selector:
    matchLabels:
      app: site
  replicas: 1
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: gcr.io/broad-ctsa/site
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: /etc/letsencrypt
            name: letsencrypt-certs
      volumes:
        - name: letsencrypt-certs
          persistentVolumeClaim:
            claimName: letsencrypt-certs
