apiVersion: v1
kind: ServiceAccount
metadata:
  name: address
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: address
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: address
subjects:
- kind: ServiceAccount
  name: address
roleRef:
  kind: Role
  name: address
  apiGroup: rbac.authorization.k8s.io
