apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: scheduler
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
       - name: scheduler
         image: "{{ scheduler_image.image }}"
         resources:
           requests:
             memory: "1G"
             cpu: "1"
         ports:
          - containerPort: 5000
         readinessProbe:
           httpGet:
             path: /healthcheck
             port: 5000
           initialDelaySeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: scheduler
