apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuffler
  labels:
    app: shuffler
spec:
  selector:
    matchLabels:
      app: shuffler
  replicas: 1
  template:
    metadata:
      labels:
        app: shuffler
    spec:
      containers:
        - name: shuffler
          image: gcr.io/hail-vdc/shuffler
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8G"
              cpu: "1"
          ports:
            - containerPort: 4999
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 4999
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 4999
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shuffler
  labels:
    app: shuffler
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4999
  selector:
    app: shuffler
