apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-agent
  namespace: {{ default_ns.name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-agent
  namespace: {{ default_ns.name }}
rules:
- apiGroups: [""]
  resources: ["services", "pods", "pods/log"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-agent
  namespace: {{ default_ns.name }}
subjects:
- kind: ServiceAccount
  name: ci-agent
  namespace: {{ default_ns.name }}
roleRef:
  kind: Role
  name: ci-agent
  apiGroup: ""
