apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbuf
spec:
  serviceName: dbuf
  selector:
    matchLabels:
      app: dbuf
  replicas: 4
  volumeClaimTemplates:
    - metadata:
        name: dbuf
      spec:
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  template:
    metadata:
      name: dbuf
      labels:
        app: dbuf
    spec:
      volumes:
       - name: deploy-config
         secret:
           optional: false
           secretName: deploy-config
      containers:
        - name: dbuf
          image: {{ dbuf_image.image }}
          args:
            - "1"
            - "--k8s-service"
            - "$(POD_NAME)"
            - "--hostname"
            - "http://$(POD_NAME).dbuf.{{ default_ns.name }}.svc.cluster.local:80"
            - "--leader-url"
            - "http://dbuf-0.dbuf.{{ default_ns.name }}.svc.cluster.local:80"
            - "--bufsize"
            - "512"
          resources:
            requests:
              memory: "3750Mi"
              cpu: "1"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HAIL_DEPLOY_CONFIG_FILE
              value: /deploy-config/deploy-config.json
          volumeMounts:
            - name: dbuf
              mountPath: "/tmp"
            - name: deploy-config
              mountPath: /deploy-config
              readOnly: true
          imagePullPolicy: Always
          ports:
           - name: port
             hostPort: 80
             containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dbuf
spec:
  clusterIP: "None"
  ports:
   - port: 80
     targetPort: 80
  selector:
    app: dbuf
