apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbuf
spec:
  serviceName: dbuf
  selector:
    matchLabels:
      app: dbuf
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: dbuf
      spec:
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  template:
    metadata:
      name: dbuf
      labels:
        daemon: dbuf
        app: dbuf
    spec:
      containers:
        - name: dbuf
          image: gcr.io/hail-vdc/dbuf
          imagePullPolicy: Always
          resources:
            requests:
              memory: "15G"
              cpu: "4"
          args: ["4", "--hostname", "$(POD_IP)"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: dbuf
              mountPath: "/tmp"
          ports:
           - name: leader
             hostPort: 5000
             containerPort: 5000
           - name: w1
             hostPort: 5001
             containerPort: 5001
           - name: w2
             hostPort: 5002
             containerPort: 5002
           - name: w3
             hostPort: 5003
             containerPort: 5003
           # - name: w4
           #   hostPort: 5004
           #   containerPort: 5004
           # - name: w5
           #   hostPort: 5005
           #   containerPort: 5005
           # - name: w6
           #   hostPort: 5006
           #   containerPort: 5006
           # - name: w7
           #   hostPort: 5007
           #   containerPort: 5007
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
---
apiVersion: v1
kind: Service
metadata:
  name: dbuf
spec:
  ports:
   - port: 5000
     targetPort: 5000
  selector:
    app: dbuf
