name: CI
on: 
  push:
    branches:
      - main
jobs:
  build-test-publish:
    # For tag pushes, we want to assure only the tag event triggers CI, not the accompanying commit:
    if: "! startsWith(github.event.head_commit.message, 'Bump ') || startsWith(github.ref, 'refs/tags/')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildenv
          channels: cpg,conda-forge,bioconda,defaults
          channel-priority: true
          python-version: 3.7

      - name: Setup build env
        run: conda install pip conda-build anaconda-client

      - name: Build package
        run: conda build conda/$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

      - name: Upload to anaconda package repository
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
          upload ${CONDA_PREFIX}/conda-bld/**/*.tar.bz2
